{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "suggestarr.fullname" . }}-config
  labels:
    {{- include "suggestarr.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  {{- if .Values.persistence.config.volumeName }}
  volumeName: {{ .Values.persistence.config.volumeName }}
  {{- end }}
{{- end }}
