{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.cache.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
  {{- if .Values.persistence.cache.storageClass }}
  {{- if (eq "-" .Values.persistence.cache.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.cache.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.cache.volumeName }}
  volumeName: {{ .Values.persistence.cache.volumeName }}
  {{- end }}
{{- end }}
