---
strategy:
  type: Recreate

image:
  repository: lscr.io/linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: latest

env:
  PUID: 1000
  PGID: 1000
  TZ: "Etc/UTC"

secureEnv: {}
  # USER: "user"
  # PASS: "pass"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

services:
  http:
    type: ClusterIP
    port: 9091
    enabled: true
  p2p:
    type: ClusterIP
    TCPPort: 51413
    UDPPort: 51413
    enabled: true

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: transmission.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

extraVolumes: []

extraVolumeMounts: []

configuration:
  override: false
  settings: |
    {
      "alt-speed-down": 50,
      "alt-speed-enabled": false,
      "alt-speed-time-begin": 540,
      "alt-speed-time-day": 127,
      "alt-speed-time-enabled": false,
      "alt-speed-time-end": 1020,
      "alt-speed-up": 50,
      "bind-address-ipv4": "0.0.0.0",
      "bind-address-ipv6": "::",
      "blocklist-enabled": false,
      "blocklist-url": "http://www.example.com/blocklist",
      "cache-size-mb": 4,
      "dht-enabled": true,
      "download-dir": "/downloads/complete",
      "download-queue-enabled": true,
      "download-queue-size": 5,
      "encryption": 1,
      "idle-seeding-limit": 30,
      "idle-seeding-limit-enabled": false,
      "incomplete-dir": "/downloads/incomplete",
      "incomplete-dir-enabled": true,
      "lpd-enabled": false,
      "message-level": 2,
      "peer-congestion-algorithm": "",
      "peer-id-ttl-hours": 6,
      "peer-limit-global": 200,
      "peer-limit-per-torrent": 50,
      "peer-port": 51413,
      "peer-port-random-high": 65535,
      "peer-port-random-low": 49152,
      "peer-port-random-on-start": false,
      "peer-socket-tos": "default",
      "pex-enabled": true,
      "port-forwarding-enabled": true,
      "preallocation": 1,
      "prefetch-enabled": 1,
      "queue-stalled-enabled": true,
      "queue-stalled-minutes": 30,
      "ratio-limit": 2,
      "ratio-limit-enabled": false,
      "rename-partial-files": true,
      "rpc-authentication-required": false,
      "rpc-bind-address": "0.0.0.0",
      "rpc-enabled": true,
      "rpc-password": "{1ddd3f1f6a71d655cde7767242a23a575b44c909n5YuRT.f",
      "rpc-port": 9091,
      "rpc-url": "/transmission/",
      "rpc-username": "",
      "rpc-host-whitelist": "127.0.0.1",
      "rpc-host-whitelist-enabled": false,
      "rpc-whitelist": "127.0.0.1",
      "rpc-whitelist-enabled": false,
      "scrape-paused-torrents-enabled": true,
      "script-torrent-done-enabled": false,
      "script-torrent-done-filename": "",
      "seed-queue-enabled": false,
      "seed-queue-size": 10,
      "speed-limit-down": 100,
      "speed-limit-down-enabled": false,
      "speed-limit-up": 100,
      "speed-limit-up-enabled": false,
      "start-added-torrents": true,
      "trash-original-torrent-files": false,
      "umask": 2,
      "upload-slots-per-torrent": 14,
      "utp-enabled": false,
      "watch-dir": "/watch",
      "watch-dir-enabled": true
    }
  folders_to_create:
    - /downloads/incomplete
    - /downloads/complete


persistence:
  config:
    enabled: false
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 100Mi
    volumeName: ""
  downloads:
    enabled: false
    empty_dir_if_disabled: true
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    volumeName: ""
  watch:
    enabled: false
    empty_dir_if_disabled: true
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    volumeName: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
