---
strategy:
  type: Recreate

image:
  repository: ghcr.io/pterodactyl/panel
  pullPolicy: IfNotPresent
  tag: latest

env:
  APP_URL: "http://example.com"
  APP_TIMEZONE: "UTC"
  APP_SERVICE_AUTHOR: "noreply@example.com"
  APP_ENV: "production"
  APP_ENVIRONMENT_ONLY: "false"
  MAIL_FROM: "noreply@example.com"
  MAIL_DRIVER: "mail"
  MAIL_HOST: ""
  MAIL_PORT: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: "false"

args: []

secureEnv:
  DB_PASSWORD: &db-password "CHANGE_ME"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  enabled: true

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: pterodactyl-panel.local
      paths:
        - path: /login
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  database:
    enabled: false
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 100Mi
    volumeName: ""
    dataSource: {}
    dataSourceRef: {}
    keepOnUninstall: false

  data:
    enabled: false
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeName: ""
    dataSource: {}
    dataSourceRef: {}
    keepOnUninstall: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: latest

  securityContext: {}

  env: {}

  args: []

  secureEnv: {}

  resources: {}

mariadb:
  image:
    repository: mariadb
    pullPolicy: IfNotPresent
    tag: latest

  securityContext: {}

  env: {}

  args: []

  secureEnv:
    MYSQL_PASSWORD: *db-password
    MYSQL_ROOT_PASSWORD: "CHANGE_ME"

  resources: {}
