---
strategy:
  type: Recreate

image:
  repository: anthonyraymond/joal
  pullPolicy: IfNotPresent
  tag: latest

env: {}

secureEnv: {}
  # USER: "user"
  # PASS: "pass"

gluetun:
  enabled: false
  image:
    repository: qmcgaw/gluetun
    pullPolicy: IfNotPresent
    tag: latest
  env: {}
  secureEnv: {}
  configFiles: {}
  privileged: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8085
  enabled: true

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: joal.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

extraVolumes: []

extraVolumeMounts: []

configuration:
  path_prefix: "joal"
  secret_token: "password"
  override: false
  config: |
    {
      "minUploadRate" : 1000,
      "maxUploadRate" : 5000,
      "simultaneousSeed" : 5,
      "client" : "transmission-3.00.client",
      "keepTorrentWithZeroLeechers" : true,
      "uploadRatioTarget": -1.0
    }

persistence:
  data:
    enabled: false
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: ""
    annotations: {}
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 100Mi
    volumeName: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
