apiVersion: v1
kind: Secret
metadata:
  name: {{ include "joal.fullname" . }}-env
  labels:
    {{- include "joal.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secureEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{ end }}
