apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "transmission.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-settings
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          env:
            - name: "OVERRIDE_CONFIG"
              value: "{{ .Values.configuration.override }}"
          command:
            - 'sh'
            - '-c'
            - 'if [ "$OVERRIDE_CONFIG" = "true" ] || [ ! -e "/config/settings.json" ]; then cp "/default_config/settings.json" "/config/settings.json"; fi'
          volumeMounts:
            - mountPath: /default_config
              name: default-config
            - mountPath: /config
              name: config
        {{- if .Values.gluetun.enabled }}
        - name: gluetun
          image: "{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
          imagePullPolicy: {{ .Values.gluetun.image.pullPolicy }}
          restartPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - NET_ADMIN
            {{- if .Values.gluetun.privileged }}
            privileged: true
            {{- end }}
          env:
            - name: FIREWALL_INPUT_PORTS
              value: "9091"
            {{- range $key, $val := .Values.gluetun.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- if and .Values.gluetun.enabled .Values.gluetun.secureEnv }}
          envFrom:
            - secretRef:
                name: {{ include "transmission.fullname" . }}-gluetun-env
          {{- end }}
          volumeMounts:
            - mountPath: /config
              name: gluetun-config
              readOnly: true
        {{- end }}
        {{- if gt (len .Values.configuration.folders_to_create) 0 }}
        - name: init-create-folders
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox
          command:
            - 'sh'
            - '-c'
            - 'mkdir -p {{ join " " .Values.configuration.folders_to_create }}'
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if or .Values.persistence.downloads.enabled .Values.persistence.downloads.empty_dir_if_disabled }}
            - mountPath: /downloads
              name: downloads
            {{- end }}
            {{- if or .Values.persistence.watch.enabled .Values.persistence.watch.empty_dir_if_disabled }}
            - mountPath: /watch
              name: watch
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "transmission.fullname" . }}-env
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - name: ttcp
              containerPort: 51413
              protocol: TCP
            - name: tudp
              containerPort: 51413
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if or .Values.persistence.downloads.enabled .Values.persistence.downloads.empty_dir_if_disabled }}
            - mountPath: /downloads
              name: downloads
            {{- end }}
            {{- if or .Values.persistence.watch.enabled .Values.persistence.watch.empty_dir_if_disabled }}
            - mountPath: /watch
              name: watch
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: default-config
          secret:
            secretName: {{ include "transmission.fullname" . }}-config
        - name: config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim | default ( printf "%s" (include "transmission.fullname" .) ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if or .Values.persistence.downloads.enabled .Values.persistence.downloads.empty_dir_if_disabled }}
        - name: downloads
          {{- if .Values.persistence.downloads.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.downloads.existingClaim | default ( printf "%s-%s" (include "transmission.fullname" .) "downloads" ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if or .Values.persistence.watch.enabled .Values.persistence.watch.empty_dir_if_disabled }}
        - name: watch
          {{- if .Values.persistence.watch.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.watch.existingClaim | default ( printf "%s-%s" (include "transmission.fullname" .) "watch" ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if and .Values.gluetun.enabled .Values.gluetun.configFiles }}
        - name: gluetun-config
          secret:
            secretName: {{ include "transmission.fullname" . }}-gluetun-config
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
