{{- if and .Values.persistence.watch.enabled (not .Values.persistence.watch.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "transmission.fullname" . }}-watch
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  accessModes:
    {{ toYaml .Values.persistence.watch.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.watch.size | quote }}
  {{- if .Values.persistence.watch.storageClass }}
  {{- if (eq "-" .Values.persistence.watch.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.watch.storageClass }}"
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.watch.volumeName }}
  volumeName: {{ .Values.persistence.watch.volumeName }}
  {{- end }}
{{- end }}
