apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-env
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secureEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{ end }}
