{{- if and .Values.gluetun.enabled .Values.gluetun.secureEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-gluetun-env
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.gluetun.secureEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{ end }}
{{- end }}
