apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.fullname" . }}-config
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
  settings.json: {{ .Values.configuration.settings | b64enc | quote }}
