apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airsonic.fullname" . }}-properties
  labels:
    {{- include "airsonic.labels" . | nindent 4 }}
data:
  airsonic.properties: |-
    {{ .Values.configuration.properties | nindent 4 }}
