apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pterodactyl-panel.fullname" . }}-redis-env
  labels:
    {{- include "pterodactyl-panel.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.redis.secureEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{ end }}
